"""empty message

Revision ID: 033d4bee4109
Revises: 5dbd69a3d548
Create Date: 2022-09-18 22:02:53.889413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '033d4bee4109'
down_revision = '5dbd69a3d548'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('servicio', 'name',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('servicio', 'precio',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('servicio', 'precio',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('servicio', 'name',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    # ### end Alembic commands ###
