"""empty message

Revision ID: 7a077e9b1451
Revises: 
Create Date: 2022-09-13 20:00:18.562575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a077e9b1451'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('avatar', sa.String(length=150), nullable=True),
    sa.Column('password', sa.String(length=150), nullable=False),
    sa.Column('salt', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('taller',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('direccion', sa.String(length=150), nullable=True),
    sa.Column('rif', sa.String(length=80), nullable=True),
    sa.Column('razon_social', sa.String(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rif')
    )
    op.create_table('servicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('precio', sa.Integer(), nullable=False),
    sa.Column('taller_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['taller_id'], ['taller.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('servicio')
    op.drop_table('taller')
    op.drop_table('user')
    # ### end Alembic commands ###
