"""empty message

Revision ID: fa08c0ff7e14
Revises: 033d4bee4109
Create Date: 2022-09-18 22:11:30.027868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa08c0ff7e14'
down_revision = '033d4bee4109'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('servicio', 'name',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('servicio', 'precio',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('servicio_name_key', 'servicio', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('servicio_name_key', 'servicio', ['name'])
    op.alter_column('servicio', 'precio',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('servicio', 'name',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    # ### end Alembic commands ###
